name: CI
on:
# - push # standard push on main or other branches
- workflow_dispatch # run manually via Github UI
# - create # i.e. tags

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Download keys
      run: |
        curl -L -o "keys.zip" "https://files-prodkeys.b-cdn.net/prodkeys/Prodkeys.net_v19.0.0.zip"
        unzip -q keys.zip
        cd Prodkeys.net_v19.0.0
        ls -lh

    - name: Build
      run: |
        zip -r static.zip *
        mkdir static
        cp index.html static/
        ls -lh static/
      shell: bash

    - name: Upload keys
      uses: actions/upload-artifact@v4
      with:
        name: keys-v19.0.0
        path: Prodkeys.net_v19.0.0

    - name: Upload static
      uses: actions/upload-artifact@v4
      with:
        name: static-latest
        path: static
